models/Menu.php
<?php
namespace hdmodules\base\models;

use Yii;
use hdmodules\base\components\ActiveRecord;
use yii\validators\StringValidator;
use yii\behaviors\TimestampBehavior;


class Menu extends ActiveRecord {
    
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return "menu";
    }

    public function attributeLabels() {
        return [
            'name' => 'Name',
            'slug' => 'Slug'
        ];
    }

    public function rules() {
        return [
            [['name', 'slug'], 'required'],
            ['name', StringValidator::className()],
            ['slug', 'match', 'pattern' => self::$SLUG_PATTERN, 'message' => Yii::t('base', 'Slug can contain only 0-9, a-z and "-" characters (max: 128).')],
            ['slug', 'default', 'value' => null],
            ['slug', 'unique'],
        ];
    }

    public function behaviors() {
        return [
            'timestampBehavior' => [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'create_time',
                'updatedAtAttribute' => 'update_time',
            ]
        ];
    }

    /**
     * Return menu items by slug
     * @return mixed
     */
    public static function getMenuItemsBySlug($slug) {

        $items = MenuItem::find()->joinWith(['menu'])->where(['`menu`.slug' => $slug, 'status' => MenuItem::STATUS_ON])->orderBy('order_num asc')->all();
        
        return $items;
    }

    /**
     * Retrieve menu items
     * @return mixed
     */
    public function getMenuItems() {
        return $this->hasMany(MenuItem::className(), ['menu_id' => 'menu_id'])->orderBy('order_num asc');
    }

}

controllers/MenuController.php
<?php
namespace hdmodules\base\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\widgets\ActiveForm;
use hdmodules\base\models\Menu;
use hdmodules\base\models\MenuItem;
use hdmodules\base\controllers\Controller;
use hdmodules\base\controllers\StatusController;

class MenuController extends Controller
{
    /**
     * @var string
     */
    public $layout = 'menu';

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'status' => [
                'class' => StatusController::className(),
                'model' => MenuItem::className(),
            ],
        ];
    }

    /**
     * List all menus
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Menu::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }
    
    /**
     * View menu
     * @return string
     */
    public function actionView($id)
    {
        $model = Menu::find()->where(['id' => $id])->one();
        //$menuItem = new MenuItem();
        $menuItem = MenuItem::find()->where(['menu_id' => $model->id, 'parent_id' => null])->orderBy(["order_num" => SORT_ASC])->all();
        return $this->render('view', [
            'items' => $menuItem,
            'model' => $model
        ]);
    }
    
    public function getTree($model_id, $items, $prefix = ''){
        $html = '';
        if($items){
            $i = 0;
            $prefix = !empty($prefix) ? $prefix . '.' : '';
            foreach ($items as $item){
                $i++;
                $children = $item->getChildren()->all();
                $counter = $prefix . $i;
                $html .= $this->renderPartial('/menu-item/_items', ['item' => $item, 'model_id' => $model_id, 'children' => $children, 'prefix' => $counter]);
            }
        }
        return $html;
    }
    /**
     * Create a menu
     * @return array|string|Response
     */
    public function actionCreate()
    {
        $model = new Menu();

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                if ($model->save()) {
                    $this->flash('success', Yii::t('base', 'Menu created'));
                    return $this->redirect(['/base/menu/index']);
                } else {
                    $this->flash('error', Yii::t('base', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    /**
     * Edit menu
     * @param $id
     * @return array|string|Response
     */
    public function actionUpdate($id)
    {
        $model = Menu::findOne($id);

        if($model === null){
            $this->flash('error', Yii::t('base', 'Not found'));
            return $this->redirect(['index']);
        }

        if(isset($_POST['Menu'])) {
            if ($model->load(Yii::$app->request->post())) {
                if(Yii::$app->request->isAjax){
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($model);
                }
                else{
                    if($model->save()){
                        $this->flash('success', Yii::t('base', 'Menu updated'));
                        return $this->redirect(['/base/menu/index']);
                    }
                    else{
                        $this->flash('error', Yii::t('base', 'Update error. {0}', $model->formatErrors()));
                    }
                    return $this->refresh();
                }
            }
        } else {
            return $this->render('edit', [
                'model' => $model
            ]);
        }
    }

    public function actionDelete($id)
    {
        if (($model = Menu::findOne($id))) {
            $model->delete();
        }
        
        return $this->redirect(['index']);
    }

}

controllers/MenuItemController.php
<?php
namespace hdmodules\base\controllers;

use Yii;
use hdmodules\base\controllers\Controller;
use hdmodules\base\models\MenuItem;
use hdmodules\base\controllers\SortableController;
use hdmodules\base\controllers\StatusController;
use yii\web\Response;
use yii\widgets\ActiveForm;

class MenuItemController extends Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => SortableController::className(),
                'model' => MenuItem::className(),
            ],
            [
                'class' => StatusController::className(),
                'model' => MenuItem::className()
            ]
        ];
    }

    /**
     * Create a menu item
     * @return array|string|Response
     */
    public function actionCreate($menu_id, $parent_id = null)
    {
        
        $model = new MenuItem();
        $menu = \hdmodules\base\models\Menu::find()->where(['id' => $menu_id])->one();
        
        $parent = null;
        if(isset($parent_id)){
            $parent = MenuItem::find()->where(['id' => $parent_id])->one();
        }
        $model->parent_id = $parent_id;
        //Redirect back if menu not exist
        if(!$menu) {
            return $this->redirect(['/base/menu/update', 'id' => $menu->menu_id]);
        }

        $model->menu_id = $menu->id;
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {

                if ($model->save()) {
                    $this->flash('success', Yii::t('base', 'Menu item created'));
                    return $this->redirect(['/base/menu/view', 'id' => $model->menu_id]);
                } else {
                    $this->flash('error', Yii::t('base', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        } else {

            return $this->render('create', [
                'model' => $model,
                'menu' => $menu,
                'parent' => $parent
            ]);
        }

    }

    /**
     * @param $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (($model = MenuItem::findOne($id))) {
            if(isset($model->children)&& !empty($model->children)){
                foreach($model->children as $child){
                    $child->delete();
                }
            }

            $model->delete();
        } else {
            $this->error = Yii::t('base', 'Not found');
        }
        return $this->formatResponse(Yii::t('base', 'Menu item deleted'));
    }

    /**
     * Edit menu
     * @param $id
     * @return array|string|Response
     */
    public function actionUpdate($id)
    {
        $model = MenuItem::findOne($id);
        $menu = \hdmodules\base\models\Menu::find()->where(['id' => $model->menu_id])->one();
        
        if($model === null){
            $this->flash('error', Yii::t('base', 'Not found'));
            return $this->redirect(['/base/menu/index']);
        }

        $model->loadTranslations_custom();
        
        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else {

                if($model->save()){
                    $this->flash('success', Yii::t('base', 'Menu item updated'));
                }
                else{
                    $this->flash('error', Yii::t('base', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        }
        else {
            return $this->render('edit', [
                'model' => $model,
                'menu' => $menu
            ]);
        }
    }

        /**
     * @param $id
     * @return mixed
     */
    public function actionUp($id)
    {
        $menu_id = MenuItem::moveUp($id);

        return $this->redirect(['menu/view', 'id' => $menu_id]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function actionDown($id)
    {
        $menu_id = MenuItem::moveDown($id);
        
        return $this->redirect(['menu/view', 'id' => $menu_id]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function actionOn($id)
    {
        return $this->changeStatus($id, MenuItem::STATUS_ON);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function actionOff($id)
    {
        return $this->changeStatus($id, MenuItem::STATUS_OFF);
    }
}

views/menu/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use hdmodules\base\multilanguage\input_widget\MultiLanguageActiveField;
?>
<?php $form = ActiveForm::begin([
    'enableAjaxValidation' => true,
    'options' => ['enctype' => 'multipart/form-data', 'class' => 'model-form']
]); ?>

<?= $form->field($model, 'name')->widget(MultiLanguageActiveField::className()) ?>
<?= $form->field($model, 'slug') ?>

<div align="right">
    <?= Html::submitButton(Yii::t('base', 'Save'), ['class' => 'btn btn-primary']) ?>
</div>

<?php ActiveForm::end(); ?>

views/menu/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;

?>
<ul class="nav nav-pills">
    <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['menu/index']) ?>">List</a>
    </li>
    
    <li <?= ($action === 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to(['create']) ?>">Create</a></li>
    <?php if($action == 'update'){ ?>
        <li class="active"><a href="#">Update</a></li>
    <?php } ?>
</ul>
<br/>

views/menu/create.php
<?php

use yii\helpers\Html;

$this->title = 'Create menu';

$this->params['breadcrumbs'][] = ['label' => 'Menu', ['base/menu/index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="x_title">
                <h2><?= Html::encode($this->title) ?></h2>


                <ul class="nav navbar-right">
                    <li><a class="collapse-link" style="cursor:pointer"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="row">

                    <div class="clearfix"></div>
                </div>

                <?= $this->render('_menu') ?> 

            </div>
            <div class="x_content">
                <div class="row">
                    <div class="col-lg-12">
                        <?= $this->render('_form', ['model' => $model]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/menu/edit.php
<?php
/**
 * @var $model hdmodules\base\models\MenuItem
 */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = sprintf('Update: (ID: %s) %s', $model->id, $model->name);

$this->params['breadcrumbs'][] = ['label' => 'Menu', ['/base/menu/index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="x_title">
                <h2><?= Html::encode($this->title) ?></h2>


                <ul class="nav navbar-right">
                    <li><a class="collapse-link" style="cursor:pointer"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="row">

                    <div class="clearfix"></div>
                </div>

                <?=
                    yii\widgets\Breadcrumbs::widget([
                        'homeLink' => [
                            'label' => 'Home',
                            'url' => Yii::$app->urlManager->baseUrl,
                        ],
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
                    ]);
                ?>

            </div>
            <div class="x_content">
                <div class="row">
                    <div class="col-lg-12">
                        <?= $this->render('_form', ['model' => $model]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/menu/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

$this->title = Yii::t('base', 'Menu');
$this->params['breadcrumbs'][] = $this->title;
?>

<?php //$this->render('_menu') ?>



<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-md-10">
        <?=
        yii\widgets\Breadcrumbs::widget([
            'homeLink' => [
                'label' => 'Home',
                'url' => Yii::$app->urlManager->baseUrl,
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []])
        ?>
    </div>
    <div class="col-md-2" align="right">
        <?= Html::a('Create', ['create'], ['class' => 'btn btn-primary']) ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            //'filterModel' => $searchModel,
            'columns' => [
                [
                    'class' => 'yii\grid\SerialColumn',
                    'contentOptions' => ['width' => '3%']
                ],
                [
                    'attribute' => 'id',
                    'contentOptions' => ['width' => '3%'],
                ],
                [
                    'attribute' => 'name',
                    'contentOptions' => ['width' => '40%'],
                ],
                [
                    'attribute' => 'slug',
                    'contentOptions' => ['width' => '10%'],
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'contentOptions' => ['width' => '3%'],
                //'template' => '{update} {delete}'
                ],
            ],
        ]);
        ?>

    </div>
</div>

views/menu/view.php
<?php

use yii\widgets\Pjax;
use yii\web\JsExpression;
use execut\widget\TreeView;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use hdmodules\base\multilanguage\input_widget\MultiLanguageActiveField;
use kartik\widgets\SwitchInput;
use yii\web\View;

$this->title = sprintf('(ID: %s) %s', $model->id, $model->name);

$this->params['breadcrumbs'][] = ['label' => 'Menu', ['index']];
$this->params['breadcrumbs'][] = $this->title;

$this->registerJs('
    function changeStatus(obj){
        console.log(obj)
        var item_id = $(obj).data("id");

        if(obj.checked){
            var url = "' . Url::to(['/base/menu-item/on']) . '";
        } else {
            var url = "' . Url::to(['/base/menu-item/off']) . '";
        }

        $.ajax({
            url: url,
            data: {id:item_id},
            method: "GET",
            dataType: "json",
            success: function(data){
                console.log(data );
            }
        });
        
    };', View::POS_END);
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-md-10">
        <?= $this->render('_menu') ?> 
    </div>
</div>
<div>
    <a class="btn btn-primary" href="<?= Url::to(['menu-item/create', 'menu_id' => $model->id]) ?>">
        <?= Yii::t("site", "Add menu item"); ?>
    </a>
    <br>
    <br>
</div>

<div class="row">
    <div class="col-md-12">
        <?= $this->context->getTree($model->id, $items) ?>
    </div>
</div>